apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-service-deployment
    namespace: ambassador
    labels:
        app: frontend-service
spec:
    replicas: 2
    selector:
        matchLabels: 
            app: frontend-service
    template:
        metadata:
            labels:
                app: frontend-service
        spec:
            containers:
            -   name: frontend-service
                imagePullPolicy: Always
                image: segment17hub/frontendservice:0.1.5
                ports:
                -   containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ambassador
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: frontend-service

---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: frontend-service-mapping
  namespace: ambassador
spec:
  prefix: /
  service: frontend-service
---
apiVersion: getambassador.io/v2
kind:  Module
metadata:
  name:  ambassador
spec:
  config:
    enable_grpc_web: true
